# Generated by Django 4.2.8 on 2023-12-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_manager_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='city',
            field=models.TextField(default=''),
        ),
    ]
